project:
  type: website

website:
  search: false
  title: "Harry Zhong"
  favicon: logo.png
  navbar:
    pinned: true
    left:
      - text: "{{<fa diagram-project>}} Projects"
        href: projects.qmd
      - text: "{{<fa calendar-check>}} Timeline"
        href: timeline/index.qmd
          
  #repo-url: https://github.com/Harry2687/my-website
  #repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

