project:
  type: website

website:
  search: false
  title: "Harry Zhong"
  navbar:
    left:
      - href: index.qmd
        text: Home
  repo-url: https://github.com/Harry2687/my-website
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: source

