project:
  type: website

website:
  search: false
  title: "Harry Zhong"
  favicon: logo.png
  navbar:
    pinned: true
    left:
      - text: Projects
        menu: 
          - text: "Spotify Analysis"
            href: projects/spotify-analysis/index.qmd
      - text: Goals
        href: goals/index.qmd
          
  #repo-url: https://github.com/Harry2687/my-website
  #repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: source

